import "./globals.css";

export const metadata = {
  title: "FG - Consórcios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" type="image/png" sizes="128x128" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
